#!/usr/bin/env python
"""Regenerate src/core/licenses.rs from `cargo metadata`.

The About dialog lists every crate mdr depends on. Keeping that list by hand
guarantees it goes stale, so generate it and let CI fail when it drifts:

    python scripts/gen-licenses.py          # rewrite the file
    python scripts/gen-licenses.py --check  # exit 1 if it is out of date

The whole resolve graph is walked, not just the default feature set, so the
list covers every backend and platform. That over-includes crates a particular
build does not link — safe for attribution, where omitting one is the failure
that matters.

Needs Python 3.7+ (subprocess capture_output). macOS system python3 is 3.6.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "core" / "licenses.rs"

# Copyright lines shown in the About dialog. Keep in sync with LICENSE,
# NOTICE.md, Cargo.toml, build.rs and packaging/ — those are not generated.
COPYRIGHT = "Copyright \u00a9 2026 Opusify IT Solutions Pvt. Ltd."
UPSTREAM_COPYRIGHT = "Copyright \u00a9 2026 Clever Cloud \u2014 original mdr, MIT"

# Assets vendored into the binary, which `cargo metadata` cannot know about.
# Keep in sync with packaging/debian/copyright.
BUNDLED = [
    ("highlight.js", "11.11.1", "BSD-3-Clause",
     "Josh Goebel and other contributors", "assets/highlight.min.js"),
    ("mermaid", "bundled", "MIT",
     "Mermaid contributors", "assets/mermaid.min.js"),
]


def crates():
    # --all-features matters: without it `cargo metadata` resolves the default
    # feature set only, which is the webview backend. Every egui and tui
    # dependency — eframe, egui_commonmark, syntect, ratatui, crossterm, ureq
    # and their trees — would then be missing from a list whose whole job is to
    # credit them. `cargo build --features egui-backend` links them all.
    meta = json.loads(subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--all-features"],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout)
    pkgs = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    root = meta["resolve"]["root"]

    seen, stack = set(), [root]
    while stack:
        i = stack.pop()
        if i in seen:
            continue
        seen.add(i)
        stack.extend(nodes.get(i, {}).get("dependencies", []))

    out = []
    for i in seen - {root}:
        p = pkgs[i]
        lic = p.get("license")
        if not lic:
            # license_file means a non-SPDX license shipped in-tree; flag it
            # rather than silently attributing nothing.
            lic = f"see {p['license_file']}" if p.get("license_file") else "UNKNOWN"
        out.append((p["name"], p["version"], lic))
    return sorted(out, key=lambda c: (c[0].lower(), c[1]))


def rs(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render():
    cs = crates()
    lines = [
        "//! Third-party attribution shown in the About dialog.",
        "//!",
        "//! GENERATED by scripts/gen-licenses.py — do not edit by hand.",
        "//! Regenerate with `python scripts/gen-licenses.py` after changing",
        "//! dependencies; CI checks this file is current.",
        "",
        "/// The fork's copyright holder, as shown in the About dialog. Also stated in",
        "/// LICENSE, NOTICE.md, Cargo.toml, build.rs and packaging/ — grep for it",
        "/// before changing, those are not generated from here.",
        f'pub const COPYRIGHT: &str = "{COPYRIGHT}";',
        "",
        "/// The upstream work this is a fork of. MIT requires its notice to travel",
        "/// with every copy, so it is shown alongside the fork's own line.",
        f'pub const UPSTREAM_COPYRIGHT: &str = "{UPSTREAM_COPYRIGHT}";',
        "",
        "/// Rust crates in mdr's dependency graph: (name, version, SPDX license).",
        "/// `static`, not `const`: a const this size is copied at every use site.",
        "/// Covers every backend and platform, so a given build may link fewer.",
        f"pub static CRATES: [(&str, &str, &str); {len(cs)}] = [",
    ]
    lines += [f'    ("{rs(n)}", "{rs(v)}", "{rs(l)}"),' for n, v, l in cs]
    lines += [
        "];",
        "",
        "/// Non-Rust assets compiled into the binary: (name, version, license,",
        "/// copyright holder, path in this repository).",
        f"pub static BUNDLED: [(&str, &str, &str, &str, &str); {len(BUNDLED)}] = [",
    ]
    lines += [f'    ("{rs(n)}", "{rs(v)}", "{rs(l)}", "{rs(c)}", "{rs(p)}"),'
              for n, v, l, c, p in BUNDLED]
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    new = render()
    if "--check" in sys.argv:
        old = OUT.read_text() if OUT.exists() else ""
        if old != new:
            print(f"{OUT.relative_to(ROOT)} is out of date — run: "
                  "python scripts/gen-licenses.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.write_text(new)
    print(f"wrote {OUT.relative_to(ROOT)}: {new.count('),')} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
